// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/hotelsdatamerge.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HotelDataMerge_GetHotels_FullMethodName = "/proto.HotelDataMerge/GetHotels"
)

// HotelDataMergeClient is the client API for HotelDataMerge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HotelDataMergeClient interface {
	GetHotels(ctx context.Context, in *GetHotelsRequest, opts ...grpc.CallOption) (*GetHotelsResponse, error)
}

type hotelDataMergeClient struct {
	cc grpc.ClientConnInterface
}

func NewHotelDataMergeClient(cc grpc.ClientConnInterface) HotelDataMergeClient {
	return &hotelDataMergeClient{cc}
}

func (c *hotelDataMergeClient) GetHotels(ctx context.Context, in *GetHotelsRequest, opts ...grpc.CallOption) (*GetHotelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotelsResponse)
	err := c.cc.Invoke(ctx, HotelDataMerge_GetHotels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelDataMergeServer is the server API for HotelDataMerge service.
// All implementations must embed UnimplementedHotelDataMergeServer
// for forward compatibility.
type HotelDataMergeServer interface {
	GetHotels(context.Context, *GetHotelsRequest) (*GetHotelsResponse, error)
	mustEmbedUnimplementedHotelDataMergeServer()
}

// UnimplementedHotelDataMergeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotelDataMergeServer struct{}

func (UnimplementedHotelDataMergeServer) GetHotels(context.Context, *GetHotelsRequest) (*GetHotelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotels not implemented")
}
func (UnimplementedHotelDataMergeServer) mustEmbedUnimplementedHotelDataMergeServer() {}
func (UnimplementedHotelDataMergeServer) testEmbeddedByValue()                        {}

// UnsafeHotelDataMergeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotelDataMergeServer will
// result in compilation errors.
type UnsafeHotelDataMergeServer interface {
	mustEmbedUnimplementedHotelDataMergeServer()
}

func RegisterHotelDataMergeServer(s grpc.ServiceRegistrar, srv HotelDataMergeServer) {
	// If the following call pancis, it indicates UnimplementedHotelDataMergeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HotelDataMerge_ServiceDesc, srv)
}

func _HotelDataMerge_GetHotels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelDataMergeServer).GetHotels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelDataMerge_GetHotels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelDataMergeServer).GetHotels(ctx, req.(*GetHotelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HotelDataMerge_ServiceDesc is the grpc.ServiceDesc for HotelDataMerge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HotelDataMerge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HotelDataMerge",
	HandlerType: (*HotelDataMergeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotels",
			Handler:    _HotelDataMerge_GetHotels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hotelsdatamerge.proto",
}
