// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/hotelsdatamerge.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIDs      []string               `protobuf:"bytes,1,rep,name=hotelIDs,proto3" json:"hotelIDs,omitempty"`
	DestinationId uint64                 `protobuf:"varint,2,opt,name=destinationId,proto3" json:"destinationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelsRequest) Reset() {
	*x = GetHotelsRequest{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsRequest) ProtoMessage() {}

func (x *GetHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotelsRequest) GetHotelIDs() []string {
	if x != nil {
		return x.HotelIDs
	}
	return nil
}

func (x *GetHotelsRequest) GetDestinationId() uint64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

type GetHotelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotels        []*Hotel               `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelsResponse) Reset() {
	*x = GetHotelsResponse{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsResponse) ProtoMessage() {}

func (x *GetHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotelsResponse) GetHotels() []*Hotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

type Hotel struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DestinationId     int64                  `protobuf:"varint,2,opt,name=destinationId,proto3" json:"destinationId,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Location          *Location              `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Amenities         *HotelAmenities        `protobuf:"bytes,6,opt,name=amenities,proto3" json:"amenities,omitempty"`
	Images            *Image                 `protobuf:"bytes,7,opt,name=images,proto3" json:"images,omitempty"`
	BookingConditions []string               `protobuf:"bytes,8,rep,name=booking_conditions,json=bookingConditions,proto3" json:"booking_conditions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{2}
}

func (x *Hotel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hotel) GetDestinationId() int64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Hotel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hotel) GetAmenities() *HotelAmenities {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Hotel) GetImages() *Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Hotel) GetBookingConditions() []string {
	if x != nil {
		return x.BookingConditions
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type HotelAmenities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	General       []string               `protobuf:"bytes,1,rep,name=general,proto3" json:"general,omitempty"`
	Room          []string               `protobuf:"bytes,2,rep,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotelAmenities) Reset() {
	*x = HotelAmenities{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotelAmenities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelAmenities) ProtoMessage() {}

func (x *HotelAmenities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelAmenities.ProtoReflect.Descriptor instead.
func (*HotelAmenities) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{4}
}

func (x *HotelAmenities) GetGeneral() []string {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *HotelAmenities) GetRoom() []string {
	if x != nil {
		return x.Room
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Site          []*Site                `protobuf:"bytes,2,rep,name=site,proto3" json:"site,omitempty"`
	Amenities     []*ImageAmenity        `protobuf:"bytes,3,rep,name=amenities,proto3" json:"amenities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{5}
}

func (x *Image) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *Image) GetSite() []*Site {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *Image) GetAmenities() []*ImageAmenity {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{6}
}

func (x *Room) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Site struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{7}
}

func (x *Site) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Site) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ImageAmenity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageAmenity) Reset() {
	*x = ImageAmenity{}
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageAmenity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageAmenity) ProtoMessage() {}

func (x *ImageAmenity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotelsdatamerge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageAmenity.ProtoReflect.Descriptor instead.
func (*ImageAmenity) Descriptor() ([]byte, []int) {
	return file_proto_hotelsdatamerge_proto_rawDescGZIP(), []int{8}
}

func (x *ImageAmenity) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ImageAmenity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_hotelsdatamerge_proto protoreflect.FileDescriptor

const file_proto_hotelsdatamerge_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/hotelsdatamerge.proto\x12\x05proto\x1a\"proto/google/api/annotations.proto\"T\n" +
	"\x10GetHotelsRequest\x12\x1a\n" +
	"\bhotelIDs\x18\x01 \x03(\tR\bhotelIDs\x12$\n" +
	"\rdestinationId\x18\x02 \x01(\x04R\rdestinationId\"9\n" +
	"\x11GetHotelsResponse\x12$\n" +
	"\x06hotels\x18\x01 \x03(\v2\f.proto.HotelR\x06hotels\"\xaa\x02\n" +
	"\x05Hotel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\rdestinationId\x18\x02 \x01(\x03R\rdestinationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\blocation\x18\x04 \x01(\v2\x0f.proto.LocationR\blocation\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x123\n" +
	"\tamenities\x18\x06 \x01(\v2\x15.proto.HotelAmenitiesR\tamenities\x12$\n" +
	"\x06images\x18\a \x01(\v2\f.proto.ImageR\x06images\x12-\n" +
	"\x12booking_conditions\x18\b \x03(\tR\x11bookingConditions\"v\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\">\n" +
	"\x0eHotelAmenities\x12\x18\n" +
	"\ageneral\x18\x01 \x03(\tR\ageneral\x12\x12\n" +
	"\x04room\x18\x02 \x03(\tR\x04room\"~\n" +
	"\x05Image\x12!\n" +
	"\x05rooms\x18\x01 \x03(\v2\v.proto.RoomR\x05rooms\x12\x1f\n" +
	"\x04site\x18\x02 \x03(\v2\v.proto.SiteR\x04site\x121\n" +
	"\tamenities\x18\x03 \x03(\v2\x13.proto.ImageAmenityR\tamenities\"<\n" +
	"\x04Room\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"<\n" +
	"\x04Site\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"D\n" +
	"\fImageAmenity\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2g\n" +
	"\x0eHotelDataMerge\x12U\n" +
	"\tGetHotels\x12\x17.proto.GetHotelsRequest\x1a\x18.proto.GetHotelsResponse\"\x15\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/hotels\x90\x02\x01B\x17Z\x15hotelsDataMerge/protob\x06proto3"

var (
	file_proto_hotelsdatamerge_proto_rawDescOnce sync.Once
	file_proto_hotelsdatamerge_proto_rawDescData []byte
)

func file_proto_hotelsdatamerge_proto_rawDescGZIP() []byte {
	file_proto_hotelsdatamerge_proto_rawDescOnce.Do(func() {
		file_proto_hotelsdatamerge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hotelsdatamerge_proto_rawDesc), len(file_proto_hotelsdatamerge_proto_rawDesc)))
	})
	return file_proto_hotelsdatamerge_proto_rawDescData
}

var file_proto_hotelsdatamerge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_hotelsdatamerge_proto_goTypes = []any{
	(*GetHotelsRequest)(nil),  // 0: proto.GetHotelsRequest
	(*GetHotelsResponse)(nil), // 1: proto.GetHotelsResponse
	(*Hotel)(nil),             // 2: proto.Hotel
	(*Location)(nil),          // 3: proto.Location
	(*HotelAmenities)(nil),    // 4: proto.HotelAmenities
	(*Image)(nil),             // 5: proto.Image
	(*Room)(nil),              // 6: proto.Room
	(*Site)(nil),              // 7: proto.Site
	(*ImageAmenity)(nil),      // 8: proto.ImageAmenity
}
var file_proto_hotelsdatamerge_proto_depIdxs = []int32{
	2, // 0: proto.GetHotelsResponse.hotels:type_name -> proto.Hotel
	3, // 1: proto.Hotel.location:type_name -> proto.Location
	4, // 2: proto.Hotel.amenities:type_name -> proto.HotelAmenities
	5, // 3: proto.Hotel.images:type_name -> proto.Image
	6, // 4: proto.Image.rooms:type_name -> proto.Room
	7, // 5: proto.Image.site:type_name -> proto.Site
	8, // 6: proto.Image.amenities:type_name -> proto.ImageAmenity
	0, // 7: proto.HotelDataMerge.GetHotels:input_type -> proto.GetHotelsRequest
	1, // 8: proto.HotelDataMerge.GetHotels:output_type -> proto.GetHotelsResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_hotelsdatamerge_proto_init() }
func file_proto_hotelsdatamerge_proto_init() {
	if File_proto_hotelsdatamerge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hotelsdatamerge_proto_rawDesc), len(file_proto_hotelsdatamerge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hotelsdatamerge_proto_goTypes,
		DependencyIndexes: file_proto_hotelsdatamerge_proto_depIdxs,
		MessageInfos:      file_proto_hotelsdatamerge_proto_msgTypes,
	}.Build()
	File_proto_hotelsdatamerge_proto = out.File
	file_proto_hotelsdatamerge_proto_goTypes = nil
	file_proto_hotelsdatamerge_proto_depIdxs = nil
}
